imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: menu.yml }
    - { resource: "@LokosUserBundle/Resources/config/services.yml" }
    - { resource: "@LokosShopBundle/Resources/config/services.yml" }
    - { resource: "@LokosApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# FosUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Lokos\UserBundle\Entity\User
#    registration:
#        form:
#            type: app_user_registration
#            validation_groups: [Default, edit]

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'LokosShopBundle::form_layout.html.twig'
    globals:
        maxPageCount: 5
        limitList:
            - 10
            - 20
            - 50
            - 100
            - 200
            - 500
        defaultLimit: "%default_limit%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ LokosShopBundle, LokosUserBundle, TwigBundle ]
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  false
            json: true
        templating_formats:
            html: false
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json ], fallback_format: ~, prefer_extension: false }
            - { path: ^/api/doc, priorities: [html], fallback_format: ~, prefer_extension: false }
            - { path: ^/*, priorities: [html], fallback_format: ~, prefer_extension: false }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
#    access_denied_listener:
#        json: true
    body_listener: true
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
#    disable_csrf_role: ROLE_API

#sensio_framework_extra:
#    view:
#        annotations: false

nelmio_api_doc:
    name: Page API

nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
      '^/':
          allow_origin: ['*']
          allow_headers: ['origin', 'content-type', 'authorization', 'apikey', 'x-access-token']
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
          max_age: 3600

jms_serializer:
    metadata:
#        auto_detection: true
        directories:
            someName:
                namespace_prefix: Lokos\ShopBundle
                path: "%kernel.root_dir%/config/serializer"
    handlers:
        datetime:
            default_format: "Y-m-d"
            default_timezone: "UTC"
#        directories:
#            FOSUserBundle:
#                namespace_prefix: FOS\UserBundle
#                path: "@MindkYachadApiBundle/Resources/config/serializer/fos"
