lokos_admin:
    resource: "@LokosAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

lokos_user:
    resource: "@LokosUserBundle/Resources/config/routing.yml"
    prefix:   /

lokos_shop:
    resource: "@LokosShopBundle/Resources/config/routing.yml"
    prefix:   /
