#lokos_api:
#    type: rest
#    prefix: api
#    resource: "@LokosApiBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

lokos_user:
    resource: "@LokosUserBundle/Resources/config/routing.yml"
    prefix:   /

lokos_shop:
    resource: "@LokosShopBundle/Resources/config/routing.yml"
    prefix:   /
