lokos_shop_homepage:
    path:     /
    defaults: { _controller: LokosShopBundle:Product:index }
lokos_shop_overview:
    path: /categories/{id}
    defaults: { _controller: LokosShopBundle:Product:overview }
    requirements:
        id: \d+

lokos_shop_add_to_cart:
    path: /cart/add/
    defaults: { _controller: LokosShopBundle:Cart:addToCart }

lokos_shop_cart:
    path: /cart/
    defaults: { _controller: LokosShopBundle:Cart:index }