parameters:
  lokos.shop.cart_repository.class: Lokos\ShopBundle\Repositories\CartRepository
  lokos.shop.generic_repository.class: Lokos\ShopBundle\Repositories\GenericRepository

services:
  lokos.shop.cart_repository:
    class: %lokos.shop.cart_repository.class%
    arguments:
      - '@doctrine.orm.entity_manager'

  lokos.shop.product_form_type:
    class: Lokos\ShopBundle\Form\Type\ProductFormType
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: form.type }]

  lokos.shop.product_to_option_form_type:
    class: Lokos\ShopBundle\Form\Type\ProductToOptionFormType
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: form.type }]

  lokos.shop.extended_collection_type:
    class: Lokos\ShopBundle\Form\Fields\ExtendedCollectionType
    tags: [{ name: form.type, alias: channel }]

#  lokos_form_optio_value_type:
#    class: Lokos\ShopBundle\Form\Type\OptionValue
#    tags:
#       -  { name: form.type }
